### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by jejer** [Plailect/PlaiCDN#7]
Script abort for some encoding issue.

C:\Users\bzhu006\Downloads\3DS>PlaiCDN.exe 000400000014F200 abb5c65ecaba9bcd29d1
bfdf3f64c285 -check
Content ID:    00000000
Content Index: 0000
Content Size:  504299520
Content Hash:  462bd463c1aa9905f6a34a6fb57ff9ec83848569fdedd4c2616339b210ee2e31

Downloading and decrypting the first 272 bytes of 00000000 for key check

Traceback (most recent call last):
  File "<string>", line 394, in <module>
UnicodeEncodeError: 'gbk' codec can't encode character '\u2122' in position 27:
illegal multibyte sequence
PlaiCDN returned -1

**Comment by Plailect** [comment]
This happens due to Windows' command prompt being unable to display characters like the trademark symbol.

I have "fixed" this in the latest version with some [instanely ugly code](https://github.com/Plailect/PlaiCDN/blob/master/PlaiCDN.py#L178-L180), but it has the side effect of showing a question mark instead of the original character.
